# Generated by Django 5.1.3 on 2024-12-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_matriculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudent',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
